In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df_lending = pd.read_csv("lending_data.csv")
# Review the DataFrame
df_lending.sample(10)

loan_size  interest_rate  borrower_income  debt_to_income  \
28083    10700.0          7.667            52700        0.430740   
9885      9800.0          7.289            49200        0.390244   
25549    10400.0          7.554            51700        0.419729   
2840      8300.0          6.642            43100        0.303944   
32515    10000.0          7.371            50000        0.400000   
22081     9500.0          7.147            47900        0.373695   
62595     9700.0          7.267            49000        0.387755   
21980    10400.0          7.542            51600        0.418605   
73535    10300.0          7.492            51100        0.412916   
64344     8900.0          6.925            45800        0.344978   

       num_of_accounts  derogatory_marks  total_debt  loan_status  
28083                5                 1       22700            0  
9885                 4                 0       19200            0  
25549                4                 1       21700            0  
2840                 2                 0       13100            0  
32515                4                 0       20000            0  
22081                4                 0       17900            0  
62595                4                 0       19000            0  
21980                4                 1       21600            0  
73535                4                 1       21100            0  
64344                3                 0       15800            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features

# Separate the X variable, the features
X = df_lending.copy()
X.drop("loan_status", axis=1, inplace=True)

# Separate the y variable, the labels
y = df_lending["loan_status"].values.reshape(-1, 1)

In [4]:
# Review the y variable Series
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [5]:
# Review the X variable DataFrame
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
# Check the balance of our target values
loan_status_count = df_lending['loan_status'].value_counts()
print(loan_status_count)

0    75036
1     2500
Name: loan_status, dtype: int64


### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)

# Fit the model using training data
lr_model = logistic_regression_model.fit(X_train, y_train)

c:\Users\krist\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
# Make a prediction using the testing data
testing_predictions = lr_model.predict(X_test)
testing_predictions[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [10]:
# Print the balanced_accuracy score of the model
accuracy = balanced_accuracy_score(y_test, testing_predictions)
print(accuracy)

0.9520479254722232


In [11]:
# Generate a confusion matrix for the model
test_matrix = confusion_matrix(y_test, testing_predictions)
print(test_matrix)

[[18663   102]
 [   56   563]]


In [12]:
# Create and save the confusion matrix for the training data
training_predictions = lr_model.predict(X_train)
training_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

training_report = classification_report(y_train, training_predictions)
print(training_report)

[[55994   277]
 [  181  1700]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56271
           1       0.86      0.90      0.88      1881

    accuracy                           0.99     58152
   macro avg       0.93      0.95      0.94     58152
weighted avg       0.99      0.99      0.99     58152



In [13]:
# Print the classification report for the model
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 

For the "0" class (healthy loan):

Precision: The model achieves a precision of 1.00, indicating that when it predicts a loan as healthy, it is correct 100% of the time.\
Recall: The model has a recall of 0.99, suggesting that it correctly identifies 99% of the actual healthy loans.\
F1-score: The F1-score, which combines precision and recall, is 1.00. This score indicates a very high overall performance for the "0" class.

For the "1" class (high-risk loan):

Precision: The precision for the high-risk loans is 0.85, indicating that when the model predicts a loan as high-ris|k, it is correct approximately 85% of the time.\
Recall: The recall is 0.91, implying that the model correctly identifies 91% of the actual high-risk loans.\
F1-score: The F1-score for the "1" class is 0.88, reflecting a reasonably good overall performance.

Overall, the model shows excellent performance in predicting healthy loans (class "0") with very high precision, recall, and F1-score. It also performs well in identifying high-risk loans (class "1") with good precision, recall, and F1-score, although not as high as for the healthy loans. The accuracy of the model is 0.99, indicating that it correctly predicts the labels for 99% of the loans in the dataset.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [14]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# Assign a random_state parameter of 1 to the model
random_state_model = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
ro_model = random_state_model.fit(X_train, y_train)

X_train_rs, y_train_rs = X_train, y_train

In [15]:
# Count the distinct values of the resampled labels data
distinct_values = np.unique(X_train_rs)
count = len(distinct_values)
print("Number of distinct values:", count)

distinct_values2 = np.unique(y_train_rs)
count = len(distinct_values)
print("Number of distinct values:", count)


Number of distinct values: 5980
Number of distinct values: 5980


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [19]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model_rs = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
lr_model_rs = logistic_regression_model_rs.fit(X_train_rs, y_train_rs)

# Make a prediction using the testing data
testing_predictions_rs = lr_model_rs.predict(X_test)


c:\Users\krist\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [17]:
# Print the balanced_accuracy score of the model 
accuracy_rs = balanced_accuracy_score(y_train_rs, testing_predictions_rs)
print(accuracy_rs)

0.9494259906569136


In [20]:
# Generate a confusion matrix for the model
testing_matrix_rs = confusion_matrix(y_test, testing_predictions_rs)
print(testing_matrix_rs)


[[18663   102]
 [   56   563]]


In [23]:
# Print the classification report for the model
testing_report_rs = classification_report(y_test, testing_predictions_rs)
print(testing_report_rs)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** YOUR ANSWER HERE!